 <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="configuracion_basedatos">
        <xs:complexType>
            <xs:sequence>
                <!-- maxOccurs unbounded indica que podemos tener un número infinito de elementos base_datos -->
                <xs:element name="base_datos" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="user" type="xs:string"></xs:element>
                            <xs:element name="password" type="xs:string"></xs:element>
                            <!-- Añadir restricción de valor mínimo y valor máximo en la etiqueta port -->
                            <!-- <xs:element name="port" type="xs:integer"> -->
                            <xs:element name="port">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minInclusive value="3000"></xs:minInclusive>
                                        <xs:maxInclusive value="6543"></xs:maxInclusive>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="max_connections" type="xs:integer"></xs:element>

                            <!-- Añadimos una restricción de valores concretos para la etiqueta access_mode -->
                            <!-- <xs:element name="access_mode" type="xs:string"> -->
                            <xs:element name="access_mode">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="local"></xs:enumeration>
                                        <xs:enumeration value="remote"></xs:enumeration>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                        <!-- Los atributos deben ir dentro del complexType del elemento al que pertenezcan, despues del cierre de la etiqueta sequence -->
                        <xs:attribute name="host" type="xs:string"></xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>
